# Generated by Django 2.1.3 on 2018-11-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=15, verbose_name='_id')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('pic', models.ImageField(max_length=128, upload_to='history', verbose_name='配图')),
                ('date', models.DateField(verbose_name='时间')),
                ('des', models.TextField(max_length=512, verbose_name='正文')),
                ('lunar', models.CharField(max_length=20, verbose_name='阴历')),
            ],
            options={
                'verbose_name': '历史上的今天',
                'verbose_name_plural': '历史上的今天',
                'db_table': 'hero_history_story',
            },
        ),
    ]
