# Generated by Django 2.0.9 on 2018-11-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historytoday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_id', models.SmallIntegerField(null=True, verbose_name='插图ID')),
                ('pic_url', models.URLField(null=True, verbose_name='图片地址')),
                ('pic_title', models.CharField(max_length=32, null=True, verbose_name='图片标题')),
            ],
            options={
                'verbose_name': '事件插图',
                'verbose_name_plural': '事件插图',
                'db_table': 'hero_history_pic',
            },
        ),
        migrations.RemoveField(
            model_name='historystory',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='historystory',
            name='des',
        ),
        migrations.RemoveField(
            model_name='historystory',
            name='lunar',
        ),
        migrations.RemoveField(
            model_name='historystory',
            name='pic',
        ),
        migrations.AddField(
            model_name='historystory',
            name='content',
            field=models.TextField(max_length=1024, null=True, verbose_name='正文呢'),
        ),
        migrations.AddField(
            model_name='historystory',
            name='day',
            field=models.CharField(max_length=10, null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='historystory',
            name='e_id',
            field=models.CharField(max_length=15, null=True, verbose_name='_id'),
        ),
        migrations.AddField(
            model_name='historystory',
            name='pic_no',
            field=models.SmallIntegerField(null=True, verbose_name='图片数量'),
        ),
        migrations.AlterField(
            model_name='historystory',
            name='date',
            field=models.CharField(max_length=20, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='historystory',
            name='title',
            field=models.CharField(max_length=64, null=True, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='storypic',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historytoday.HistoryStory', verbose_name='文章'),
        ),
    ]
