# Generated by Django 2.0.9 on 2018-11-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historytoday', '0002_auto_20181115_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historystory',
            name='e_id',
            field=models.SmallIntegerField(null=True, verbose_name='_id'),
        ),
    ]
